### PR TITLE
GPO sec filtering and ac not compliant with ms adts

### PR DESCRIPTION
**Pull request by thor-sssd**
Thank you for rebasing the original Pagure pull request and moving it to GitHub. Due to recent changes in code the long-running pull-request did not build anymore.
I have checked the code, adapted the patches to comply with the latest SSSD baseline and successfully built it on arch-linux.

Please check and update the official PR.

### CODE REVIEW

**Comment by elkoniu** [comment]
Thanks for this PR Thomas, now it is more straight forward related to master. I will replace my upstream PR with those commits. Have you been able to test this recently or some extra testing is needed?

**Comment by elkoniu** [comment]
Small update: I just pushed those commits to upstream PR. So upstream PR will be identical with this one and content of commits will be the same. If you will have any changes to add feel free to push them here and I will forward them to upstream.

**Comment by thor-sssd** [comment]
Thank you for pushing the commits. I've been testing the changes in a network using Samba AD (Version 4.7.6-Ubuntu) and an Arch Linux file server as well as for comparison on a Windows 7 workstation.
The original patches have been running in a productive environment since 2017.

**Comment by elkoniu** [comment]
Could you comment also those test results on upstream pull request? It may speed up confirming and merging process. I will keep this fork pull request open until upstream one will be merged and closed. I think then we will be also able to close original one on Pagure.

**Comment by thor-sssd** [comment]
You're challenging me. At least the test results look better than the initial ones. But why all clients are passed but fedora rawhide not is not self-explaining. I can only see a timeout notification and maybe hanging valgrind test pam-srv-tests. The same timeout happened also to PR #1020.

I tried to setup sssd_test_suite today but it heavily harms my machine's environment and I had to cancel.

Any recommendation?

**Comment by elkoniu** [comment]
This is very good question! I know that our test environment from time to time can behave a bit "unstable" related to some test branches. Will check that on the morning to confirm this is not related to test environment itself.

**Comment by thor-sssd** [comment]
Finally I have setup sssd_test_suite here on the workstation. All tests pass except for Fedora Rawhide. Check Valgrind tests hang. Digging into the logs outline  pam-srv-tests as problem:
```
    child_pid = fork();
    if (child_pid == 0) { /* child */
        ret = execlp("certutil", "certutil", "-N", "--empty-password", "-d",
                     NSS_DB_2CERTS, NULL);
        if (ret == -1) {
            DEBUG(SSSDBG_FATAL_FAILURE, "execl() failed.\n");
            exit(-1);
        }
    } else if (child_pid > 0) {
        wait(&status);
    } else {
        ret = errno;
        DEBUG(SSSDBG_FATAL_FAILURE, "fork() failed\n");
        return ret;
    }

```
Command 
```
certutil -N --empty-password -d sql:tp_pam_srv_tests-test_pam_srv_2certs`
```
runs forever and seems to trigger the timeout. When manually killing the process we can experience further hangs of the certutil command for the other certs. But pam-srv-tests complete successfully with following log:

```
. . .
[ RUN      ] test_pam_preauth_cert_nocert              
(Tue Apr 21 20:11:42:372717 2020) [sssd] [child_sig_handler] (0x0020): child [401828] failed with status [1].
[       OK ] test_pam_preauth_cert_nocert    
[ RUN      ] test_pam_preauth_cert_nomatch   
[       OK ] test_pam_preauth_cert_nomatch   
[ RUN      ] test_pam_preauth_cert_match
[       OK ] test_pam_preauth_cert_match                                                                             
[ RUN      ] test_pam_preauth_cert_match_gdm_smartcard
[       OK ] test_pam_preauth_cert_match_gdm_smartcard
[ RUN      ] test_pam_preauth_cert_match_wrong_user
[       OK ] test_pam_preauth_cert_match_wrong_user
[ RUN      ] test_pam_preauth_cert_no_logon_name
[       OK ] test_pam_preauth_cert_no_logon_name
[ RUN      ] test_pam_preauth_cert_no_logon_name_with_hint 
[       OK ] test_pam_preauth_cert_no_logon_name_with_hint 
[ RUN      ] test_pam_preauth_cert_no_logon_name_double_cert
(Tue Apr 21 20:12:01:931384 2020) [sssd] [pam_forwarder_lookup_by_cert_done] (0x0020): More than one user mapped to certificate.
[       OK ] test_pam_preauth_cert_no_logon_name_double_cert
[ RUN      ] test_pam_preauth_cert_no_logon_name_double_cert_with_hint
[       OK ] test_pam_preauth_cert_no_logon_name_double_cert_with_hint
[ RUN      ] test_pam_preauth_no_cert_no_logon_name
(Tue Apr 21 20:12:06:540445 2020) [sssd] [pam_forwarder_cert_cb] (0x0020): No certificate found and no logon name given, authentication not possible.
[       OK ] test_pam_preauth_no_cert_no_logon_name
[ RUN      ] test_pam_preauth_cert_no_logon_name_no_match
(Tue Apr 21 20:12:06:636007 2020) [sssd] [child_sig_handler] (0x0020): waitpid did not found a child with changed status.
(Tue Apr 21 20:12:09:252182 2020) [sssd] [pam_forwarder_lookup_by_cert_done] (0x0020): Missing logon name and no certificate user found.
[       OK ] test_pam_preauth_cert_no_logon_name_no_match
[ RUN      ] test_pam_cert_auth
[       OK ] test_pam_cert_auth
[ RUN      ] test_pam_cert_auth
[       OK ] test_pam_cert_auth
[ RUN      ] test_pam_ecc_cert_auth
[       OK ] test_pam_ecc_cert_auth
[ RUN      ] test_pam_cert_auth_double_cert
[       OK ] test_pam_cert_auth_double_cert
[ RUN      ] test_pam_cert_preauth_2certs_one_mapping
[       OK ] test_pam_cert_preauth_2certs_one_mapping
[ RUN      ] test_pam_cert_preauth_2certs_two_mappings
[       OK ] test_pam_cert_preauth_2certs_two_mappings
[ RUN      ] test_pam_cert_auth_2certs_one_mapping
[       OK ] test_pam_cert_auth_2certs_one_mapping
[ RUN      ] test_pam_cert_auth_no_logon_name
[       OK ] test_pam_cert_auth_no_logon_name
[ RUN      ] test_pam_cert_auth_no_logon_name_no_key_id
(Tue Apr 21 20:12:37:043761 2020) [sssd] [pam_forwarder_parse_data] (0x0020): Missing logon and Smartcard key ID during authentication.
[       OK ] test_pam_cert_auth_no_logon_name_no_key_id
[ RUN      ] test_pam_cert_preauth_uri_token1
[       OK ] test_pam_cert_preauth_uri_token1
[ RUN      ] test_pam_cert_preauth_uri_token2
[       OK ] test_pam_cert_preauth_uri_token2
[ RUN      ] test_pam_preauth_ocsp
(Tue Apr 21 20:12:44:924739 2020) [sssd] [child_sig_handler] (0x0020): child [402165] failed with status [1].
[       OK ] test_pam_preauth_ocsp
[ RUN      ] test_pam_preauth_ocsp_no_ocsp
[       OK ] test_pam_preauth_ocsp_no_ocsp
[ RUN      ] test_pam_preauth_ocsp_soft_ocsp
[       OK ] test_pam_preauth_ocsp_soft_ocsp
[ RUN      ] test_filter_response
[       OK ] test_filter_response
[ RUN      ] test_appsvc_posix_dom
[       OK ] test_appsvc_posix_dom
[ RUN      ] test_not_appsvc_posix_dom
[       OK ] test_not_appsvc_posix_dom
[ RUN      ] test_appsvc_app_dom
[       OK ] test_appsvc_app_dom
[ RUN      ] test_not_appsvc_app_dom
[       OK ] test_not_appsvc_app_dom
[==========] 61 test(s) run.
[  PASSED  ] 61 test(s).
PASS pam-srv-tests (exit status: 0)
```
For me it seems to be an issue of the test environment. Hope this helps you.

**Comment by elkoniu** [comment]
I was speaking with other team members today and this test fails even in case of MAN page change in the repository. I think we can clearly assume it is issue related to CI rather than code itself. I will update upstream PR with right flags and move it closer to final merge. Thank you for the time spent on testing this.

**Comment by elkoniu** [comment]
Hi Thor, code has been reviewed on upstream - Sumit has 2 suggestions but quite lightweight, please take a look: https://github.com/SSSD/sssd/pull/1022

**Comment by elkoniu** [comment]
If I will see any update in this PR I will sync it with upstream. You can also try to push to upstream PR directly (not sure if this will work as it is set up from my fork, still - you are the author of commits).

**Comment by thor-sssd** [comment]
I have updated the PR as recommended by Summit, built the package and tested proper GPO file retrieval for upper case path names. We can sync it with upstream. Better to follow the working way. :-)

**Comment by elkoniu** [comment]
Thank you Thor, I have just pushed latest changes to upstream PR

**Comment by elkoniu** [comment]
Thank you for you work Thor. Upstream PR has been closed and merged so I am closing this proxy one. Again sorry that it took that long since original PR on Pagure has been created.

**Comment by thor-sssd** [comment]
Dear Pavel,
thank you very much for your support. It was great to have an powerful expert by my side.
One more question: What are your release plans for SSSD? I ask because the fixes here were just a starting point to clean-up SSSD's GPO application. There are several further issues. Some of them already popped up since 2017. Others are still hidden and have not been recognized by system admins. I wanted to wait with pushing further fixes to SSSD until this PR has been approved. The changes have been implemented since 2017, continuously adapted to the changing GPO parts of SSSD and used in production environment. What do you believe to be a good point in time to publish them to Github? 
Best regards
Thomas

**Comment by elkoniu** [comment]
Hi Thor,

Thank you for warm words, I am glad I could help with pushing your work to upstream.
I am new in GPO but this is my point of interest in SSSD for incoming months. I saw that your commits has been already merged to upstream. Our way of working is bit different as merge is done offline and then pushed to upstream rather than using dedicated GitHub "buttons".
We are in moment of transition from old Pagure issues to GitHub only. You can already see a lots of Pagure issues reforged directly to GitHub ones on upstream SSSD repo page. This is part of unifying code handling for SSSD. Meanwhile team is trying to check all existing (possible old) issues / pull requests and prioritize work on them.

If you have some existing PR on Pagure related to GPO please point me them and I will try to put them more toward front of the queue. If they need revisiting and rebasing feel free to open upstream PR yourself. If there will be some delay in review process or any help needed ping me directly.

As for the changes / issues related to GPO - you mean some project proposals or more like unsolved bugs found since 2017?

Best regards,
Pawel

**Comment by thor-sssd** [comment]
Hi Pavel,
sorry for the late answer. I wanted to add some further unit tests to the new series of patches. You will find a new PR in your repo. I wanted to show the PR to you before pushing it to the community. Please briefly check and provide me with some advice/comments.

Please note that the PR contains some more commits, as your fork was not updated to SSSD upstream.

Best regards

Thomas

**Comment by elkoniu** [comment]
Hi Thomas,

Thank you for new PR, I will take a look on it as soon I will have some spare time.
Right now I have some urgent PR to look at so it may end up that I will be able to do review in about 2 weeks. It may be worth to put them upstream directly as there is better chance that someone will be able to look at them right away.

One question from me: there are about 21 unique commits in this PR.
If any of them has been already submitted to Pagure in the past?
I am asking because all PR / issues from Pagure should be already moved to GitHub. This way it may be worth to attach respective commits to existing PR / issues inherited from Pagure.
If not then still - if there is a chance to divide those commits into few batches? I know from my experience that PRs with lots of commits attached to them are usually reviewed slower.
The best practice I saw is to publish standalone change (including eventually tests for it) as separated PR. Then bunch of those changes can be picked up one by one by different persons.

Best regards,
Pawel

**Comment by elkoniu** [comment]
Btw: have you ever thought about working for RedHat? :)

**Comment by thor-sssd** [comment]
Hi Pavel,
thank you for your quick feedback. I'm glad to have you as support. Below you find more information on your questions:

> One question from me: there are about 21 unique commits in this PR.
> If any of them has been already submitted to Pagure in the past?

None of the new commits have been submitted, yet. Neither to Pagure nor to GitHub. I wanted to wait the long-running PR to be merged before.

> If not then still - if there is a chance to divide those commits into few batches? I know from my experience that PRs with lots of commits attached to them are usually reviewed slower.
> The best practice I saw is to publish standalone change (including eventually tests for it) as separated PR. Then bunch of those changes can be picked up one by one by different persons.
> 

This is a good hint. I would follow your proposal but I have again the issue that the several PRs at least partly depend on previous ones. As far as I know GitHub does not support this. We would need a good strategy for this. One idea would be the following:
Immediate fixes, to be merged asap:
```
GPO: Group policy search not in line with [MS-GPOL]
GPO: Align names and parameters to [MS-GPOL]
```
Major changes that introduce the design changes of SSSD GPO application (see [figure](https://github.com/rdratlos/sssd/blob/feature/final_gpo_engine_doc/src/doc/sssd_ad_gpo_tevent_request_overview.pdf)) required for adding the subsequent fixes.
```
GPO: Introduce group policy application core engine
GPO: Wrong group policy target is used for DACL filtering
```
I would be glad to have these four commits merged as soon as possible. Once they are in the code it's easier to split the remaining commits into packages for more parallelized review. But I need at least one member of the development team to get a full picture of the changes, the strategy behind and the pros and cons. Having followed the conversations on Github and Pagure for some years now I believe that the high work-load of the team will discourage people to spend time on isolated design change reviews.

What do you think?

**Comment by thor-sssd** [comment]
> Btw: have you ever thought about working for RedHat? :)

:-))
RedHat is an interesting company. But you should know that I'm not a software developer but systems engineer. Currently, I work for Airbus and off-time I support some system admins to manage and improve their networks.

**Comment by elkoniu** [comment]
Hi Thor,

I am very sorry for delay in my answer. We had some work to do in the team and I was off a little bit to.
I totally agree with you idea dividing commits into urgent one and then rest of them. The best person to handle GPO related things is Summit Bose as he has big experience in this domain. As we approaching holiday season in many countries our upstream reviews can be delayed a little bit. But my holidays are planned to be at the end of the year so I can be the person fully focused on those GPO related PR.

Feel free to push them any time you want and mark me in the comment. I am trying to track latest PR but sometimes I can miss something submitted recently.

For the working in RedHat  - I am electronic engineer with background experience related to end to end design and manufacturing microcontroller driven systems, now I switched to be software engineer and playing with hardware in my free time only. So there is always an option to taste something new ;)

**Comment by thor-sssd** [comment]
Hi Pavel,

good to hear you are back and well despite of all the crisis in US and the world. 

Would it be possible fro you to inform Summit in advance that you are in touch with someone who proposes to improve SSSD AD GPO framework design to be more in line with group policy specifications, which makes it easier and more efficient to fix current and future bugs as well as adapt the code to future changes in spec? If you can forward the two figures by PR #4 and get a preliminary feedback from Summit, it will help me to split PR #4 into the right sequence of batches.

I hold microcontroller systems experts in highest regard. Especially, when it comes to (automated) testing. Excelent background, my compliments.

Best regards

Thomas

**Comment by elkoniu** [comment]
Hi Thomas,

Thank you for warm words, I can tell the same for system engineers, especially related to aviation or military grade solutions:)
I will ask Summit to take a look at https://github.com/elkoniu/sssd/pull/4 and advice how to pump it to upstream the right way.
Will keep you updated in this thread.

Best,
Pawel

**Comment by elkoniu** [comment]
I just checked and Summit is on holidays till end of the month so there is quite small chance he will be able to advice us meanwhile. There are two options here: wait for Summit to come back from holidays or try to divide it by ourselves and then push it to upstream PR. In case of 2nd option we will be able to start review process earlier - still we may end up waiting for Summit final confirmation that those changes are OK.

**Pull request closed without merging**
